### ISSUE TITLE
PVR icons

### ISSUE THREAD

**Issue by myraspxbmc** [braz96/skin.omni#1]
Hi, Can you please take a look to PVR icons.. TV and Radio use: extras/icons/back.png

**Comment by braz96** [comment]
Where are you seeing this, on the main menu? If you have created new menu items, you may need to select their icon in the menu customizer.

**Comment by myraspxbmc** [comment]
Yeap, on main Menu... And yes i can select the icon in the menu customizer, but is missing radio.png, or not?

**Comment by braz96** [comment]
I can add one for radio, will look for a good one.

**Comment by braz96** [comment]
I added a radio.png, plus a few other new ones.
